from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder.models.airway_junction_detail_input import AirwayJunctionDetailInput
from discovery_finder import util

from discovery_finder.models.airway_junction_detail_input import AirwayJunctionDetailInput  # noqa: E501

class AirwayJunctionInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, type=None, airways=None):  # noqa: E501
        """AirwayJunctionInput - a model defined in OpenAPI

        :param id: The id of this AirwayJunctionInput.  # noqa: E501
        :type id: str
        :param name: The name of this AirwayJunctionInput.  # noqa: E501
        :type name: str
        :param type: The type of this AirwayJunctionInput.  # noqa: E501
        :type type: str
        :param airways: The airways of this AirwayJunctionInput.  # noqa: E501
        :type airways: List[AirwayJunctionDetailInput]
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'type': str,
            'airways': List[AirwayJunctionDetailInput]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type',
            'airways': 'airways'
        }

        self._id = id
        self._name = name
        self._type = type
        self._airways = airways

    @classmethod
    def from_dict(cls, dikt) -> 'AirwayJunctionInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AirwayJunction-Input of this AirwayJunctionInput.  # noqa: E501
        :rtype: AirwayJunctionInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this AirwayJunctionInput.


        :return: The id of this AirwayJunctionInput.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this AirwayJunctionInput.


        :param id: The id of this AirwayJunctionInput.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this AirwayJunctionInput.


        :return: The name of this AirwayJunctionInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AirwayJunctionInput.


        :param name: The name of this AirwayJunctionInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this AirwayJunctionInput.


        :return: The type of this AirwayJunctionInput.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AirwayJunctionInput.


        :param type: The type of this AirwayJunctionInput.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def airways(self) -> List[AirwayJunctionDetailInput]:
        """Gets the airways of this AirwayJunctionInput.


        :return: The airways of this AirwayJunctionInput.
        :rtype: List[AirwayJunctionDetailInput]
        """
        return self._airways

    @airways.setter
    def airways(self, airways: List[AirwayJunctionDetailInput]):
        """Sets the airways of this AirwayJunctionInput.


        :param airways: The airways of this AirwayJunctionInput.
        :type airways: List[AirwayJunctionDetailInput]
        """
        if airways is None:
            raise ValueError("Invalid value for `airways`, must not be `None`")  # noqa: E501

        self._airways = airways
