from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder import util


class ApplicationType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DRONE_CORRIDOR = 'drone_corridor'
    JOINT_DELIVERY_HIGHWAY = 'joint_delivery_highway'
    JOINT_DELIVERY_LAST_MILE = 'joint_delivery_last_mile'
    def __init__(self):  # noqa: E501
        """ApplicationType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationType of this ApplicationType.  # noqa: E501
        :rtype: ApplicationType
        """
        return util.deserialize_model(dikt, cls)
