from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder import util


class AvailabilityEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    HEALTHY = 'healthy'
    UNHEALTHY = 'unhealthy'
    def __init__(self):  # noqa: E501
        """AvailabilityEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AvailabilityEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AvailabilityEnum of this AvailabilityEnum.  # noqa: E501
        :rtype: AvailabilityEnum
        """
        return util.deserialize_model(dikt, cls)
