from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder import util


class DronePortType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_3 = 3
    def __init__(self):  # noqa: E501
        """DronePortType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DronePortType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DronePortType of this DronePortType.  # noqa: E501
        :rtype: DronePortType
        """
        return util.deserialize_model(dikt, cls)
