from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder import util


class Geometry(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, coordinates=None):  # noqa: E501
        """Geometry - a model defined in OpenAPI

        :param type: The type of this Geometry.  # noqa: E501
        :type type: str
        :param coordinates: The coordinates of this Geometry.  # noqa: E501
        :type coordinates: List[List[str]]
        """
        self.openapi_types = {
            'type': str,
            'coordinates': List[List[str]]
        }

        self.attribute_map = {
            'type': 'type',
            'coordinates': 'coordinates'
        }

        self._type = type
        self._coordinates = coordinates

    @classmethod
    def from_dict(cls, dikt) -> 'Geometry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Geometry of this Geometry.  # noqa: E501
        :rtype: Geometry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this Geometry.


        :return: The type of this Geometry.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Geometry.


        :param type: The type of this Geometry.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def coordinates(self) -> List[List[str]]:
        """Gets the coordinates of this Geometry.


        :return: The coordinates of this Geometry.
        :rtype: List[List[str]]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates: List[List[str]]):
        """Sets the coordinates of this Geometry.


        :param coordinates: The coordinates of this Geometry.
        :type coordinates: List[List[str]]
        """
        if coordinates is None:
            raise ValueError("Invalid value for `coordinates`, must not be `None`")  # noqa: E501

        self._coordinates = coordinates
