from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder.models.validation_error import ValidationError
from discovery_finder import util

from discovery_finder.models.validation_error import ValidationError  # noqa: E501

class HTTPValidationError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, detail=None):  # noqa: E501
        """HTTPValidationError - a model defined in OpenAPI

        :param detail: The detail of this HTTPValidationError.  # noqa: E501
        :type detail: List[ValidationError]
        """
        self.openapi_types = {
            'detail': List[ValidationError]
        }

        self.attribute_map = {
            'detail': 'detail'
        }

        self._detail = detail

    @classmethod
    def from_dict(cls, dikt) -> 'HTTPValidationError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HTTPValidationError of this HTTPValidationError.  # noqa: E501
        :rtype: HTTPValidationError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail(self) -> List[ValidationError]:
        """Gets the detail of this HTTPValidationError.


        :return: The detail of this HTTPValidationError.
        :rtype: List[ValidationError]
        """
        return self._detail

    @detail.setter
    def detail(self, detail: List[ValidationError]):
        """Sets the detail of this HTTPValidationError.


        :param detail: The detail of this HTTPValidationError.
        :type detail: List[ValidationError]
        """

        self._detail = detail
