from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder import util


class LocationInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """LocationInner - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'LocationInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Location_inner of this LocationInner.  # noqa: E501
        :rtype: LocationInner
        """
        return util.deserialize_model(dikt, cls)
