from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder.models.airway_input import AirwayInput
from discovery_finder import util

from discovery_finder.models.airway_input import AirwayInput  # noqa: E501

class PutAirwayDefinitionParameters(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, airway=None):  # noqa: E501
        """PutAirwayDefinitionParameters - a model defined in OpenAPI

        :param airway: The airway of this PutAirwayDefinitionParameters.  # noqa: E501
        :type airway: AirwayInput
        """
        self.openapi_types = {
            'airway': AirwayInput
        }

        self.attribute_map = {
            'airway': 'airway'
        }

        self._airway = airway

    @classmethod
    def from_dict(cls, dikt) -> 'PutAirwayDefinitionParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PutAirwayDefinitionParameters of this PutAirwayDefinitionParameters.  # noqa: E501
        :rtype: PutAirwayDefinitionParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def airway(self) -> AirwayInput:
        """Gets the airway of this PutAirwayDefinitionParameters.


        :return: The airway of this PutAirwayDefinitionParameters.
        :rtype: AirwayInput
        """
        return self._airway

    @airway.setter
    def airway(self, airway: AirwayInput):
        """Sets the airway of this PutAirwayDefinitionParameters.


        :param airway: The airway of this PutAirwayDefinitionParameters.
        :type airway: AirwayInput
        """
        if airway is None:
            raise ValueError("Invalid value for `airway`, must not be `None`")  # noqa: E501

        self._airway = airway
