from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder.models.drone_port_details import DronePortDetails
from discovery_finder import util

from discovery_finder.models.drone_port_details import DronePortDetails  # noqa: E501

class PutDronePortReferenceParameters(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, drone_port_details=None):  # noqa: E501
        """PutDronePortReferenceParameters - a model defined in OpenAPI

        :param drone_port_details: The drone_port_details of this PutDronePortReferenceParameters.  # noqa: E501
        :type drone_port_details: DronePortDetails
        """
        self.openapi_types = {
            'drone_port_details': DronePortDetails
        }

        self.attribute_map = {
            'drone_port_details': 'drone_port_details'
        }

        self._drone_port_details = drone_port_details

    @classmethod
    def from_dict(cls, dikt) -> 'PutDronePortReferenceParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PutDronePortReferenceParameters of this PutDronePortReferenceParameters.  # noqa: E501
        :rtype: PutDronePortReferenceParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def drone_port_details(self) -> DronePortDetails:
        """Gets the drone_port_details of this PutDronePortReferenceParameters.


        :return: The drone_port_details of this PutDronePortReferenceParameters.
        :rtype: DronePortDetails
        """
        return self._drone_port_details

    @drone_port_details.setter
    def drone_port_details(self, drone_port_details: DronePortDetails):
        """Sets the drone_port_details of this PutDronePortReferenceParameters.


        :param drone_port_details: The drone_port_details of this PutDronePortReferenceParameters.
        :type drone_port_details: DronePortDetails
        """
        if drone_port_details is None:
            raise ValueError("Invalid value for `drone_port_details`, must not be `None`")  # noqa: E501

        self._drone_port_details = drone_port_details
