from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder import util


class QuerySingleAirwayDefinitionResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, url=None):  # noqa: E501
        """QuerySingleAirwayDefinitionResponse - a model defined in OpenAPI

        :param url: The url of this QuerySingleAirwayDefinitionResponse.  # noqa: E501
        :type url: str
        """
        self.openapi_types = {
            'url': str
        }

        self.attribute_map = {
            'url': 'url'
        }

        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'QuerySingleAirwayDefinitionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QuerySingleAirwayDefinitionResponse of this QuerySingleAirwayDefinitionResponse.  # noqa: E501
        :rtype: QuerySingleAirwayDefinitionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this QuerySingleAirwayDefinitionResponse.


        :return: The url of this QuerySingleAirwayDefinitionResponse.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this QuerySingleAirwayDefinitionResponse.


        :param url: The url of this QuerySingleAirwayDefinitionResponse.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url
