from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder.models.airway_output import AirwayOutput
from discovery_finder import util

from discovery_finder.models.airway_output import AirwayOutput  # noqa: E501

class SingleAirwayDefinitionResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, airway=None):  # noqa: E501
        """SingleAirwayDefinitionResponse - a model defined in OpenAPI

        :param airway: The airway of this SingleAirwayDefinitionResponse.  # noqa: E501
        :type airway: AirwayOutput
        """
        self.openapi_types = {
            'airway': AirwayOutput
        }

        self.attribute_map = {
            'airway': 'airway'
        }

        self._airway = airway

    @classmethod
    def from_dict(cls, dikt) -> 'SingleAirwayDefinitionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SingleAirwayDefinitionResponse of this SingleAirwayDefinitionResponse.  # noqa: E501
        :rtype: SingleAirwayDefinitionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def airway(self) -> AirwayOutput:
        """Gets the airway of this SingleAirwayDefinitionResponse.


        :return: The airway of this SingleAirwayDefinitionResponse.
        :rtype: AirwayOutput
        """
        return self._airway

    @airway.setter
    def airway(self, airway: AirwayOutput):
        """Sets the airway of this SingleAirwayDefinitionResponse.


        :param airway: The airway of this SingleAirwayDefinitionResponse.
        :type airway: AirwayOutput
        """
        if airway is None:
            raise ValueError("Invalid value for `airway`, must not be `None`")  # noqa: E501

        self._airway = airway
