from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from discovery_finder.models.base_model import Model
from discovery_finder import util


class SingleDiscoveryServiceDetail(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, url=None, domain=None):  # noqa: E501
        """SingleDiscoveryServiceDetail - a model defined in OpenAPI

        :param url: The url of this SingleDiscoveryServiceDetail.  # noqa: E501
        :type url: str
        :param domain: The domain of this SingleDiscoveryServiceDetail.  # noqa: E501
        :type domain: str
        """
        self.openapi_types = {
            'url': str,
            'domain': str
        }

        self.attribute_map = {
            'url': 'url',
            'domain': 'domain'
        }

        self._url = url
        self._domain = domain

    @classmethod
    def from_dict(cls, dikt) -> 'SingleDiscoveryServiceDetail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SingleDiscoveryServiceDetail of this SingleDiscoveryServiceDetail.  # noqa: E501
        :rtype: SingleDiscoveryServiceDetail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this SingleDiscoveryServiceDetail.


        :return: The url of this SingleDiscoveryServiceDetail.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this SingleDiscoveryServiceDetail.


        :param url: The url of this SingleDiscoveryServiceDetail.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def domain(self) -> str:
        """Gets the domain of this SingleDiscoveryServiceDetail.


        :return: The domain of this SingleDiscoveryServiceDetail.
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain: str):
        """Sets the domain of this SingleDiscoveryServiceDetail.


        :param domain: The domain of this SingleDiscoveryServiceDetail.
        :type domain: str
        """
        if domain is None:
            raise ValueError("Invalid value for `domain`, must not be `None`")  # noqa: E501

        self._domain = domain
